ALTER TABLE leads
ADD COLUMN IF NOT EXISTS buyer_purpose TEXT,
ADD COLUMN IF NOT EXISTS buyer_property_type TEXT,
ADD COLUMN IF NOT EXISTS buyer_typology TEXT,
ADD COLUMN IF NOT EXISTS buyer_needs_financing BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS buyer_will_sell_to_buy BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS seller_property_type TEXT,
ADD COLUMN IF NOT EXISTS seller_typology TEXT,
ADD COLUMN IF NOT EXISTS seller_location TEXT,
ADD COLUMN IF NOT EXISTS birthday DATE;